services:
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # ports:
      # - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/student_portal
    networks:
      - nginx_proxy_manager

  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=student_portal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - nginx_proxy_manager

# volumes:
#  postgres_data:
networks:
  nginx_proxy_manager:
    name: nginx-proxy-manager_default
    external: true
