version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn student_portal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./student_portal:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external: true
    name: nginx-proxy-manager_default

