# Generated by Django 4.2.7 on 2024-10-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_workshop_labequipment_studentprofile_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='lab_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='lab_password',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='workshop',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lab_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portal.labequipment'),
        ),
    ]
