# Generated by Django 4.2.7 on 2024-10-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20241005_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
