# Generated by Django 4.2.7 on 2024-10-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_rename_sent_at_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.TextField(default='Hello {{ user.first_name }},\n\nThis is a default notification template.', help_text='Jinja2 template for the notification message'),
        ),
    ]
